---

- name: add packages.sury.org apt repo
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present
  register: phpaptrepo

- name: update apt
  apt: update_cache=yes
  when: phpaptrepo.changed

- name: install php dependencies
  apt: name={{ item }} state=present
  with_items:
    - 'php5.6'
    - 'php5.6-bcmath'
    - 'php5.6-bz2'
    - 'php5.6-cli'
    - 'php5.6-common'
    - 'php5.6-curl'
    - 'php5.6-dba'
    - 'php5.6-dev'
    - 'php5.6-gd'
    - 'php5.6-json'
    - 'php5.6-ldap'
    - 'php5.6-mbstring'
    - 'php5.6-mcrypt'
    - 'php5.6-mysql'
    - 'php5.6-opcache'
    - 'php5.6-readline'
    - 'php5.6-soap'
    - 'php5.6-xml'
    - 'php5.6-zip'
    - 'php5.6-pgsql'
    - 'php5-memcached'
    - 'libapache2-mod-php5.6'
    - 'php-redis'
    - 'php5-imagick'
    - 'php-pear'
    - 'php-uploadprogress'
    - 'imagemagick'

- name: install redis
  apt:
    name: redis-server
    state: present

- name: install memcached
  apt:
    name: memcached
    state: present

- name: craete php log dir
  file:
    path: /var/log/php
    state: directory
    mode: 0755
    owner: www-data
    group: root

- name: create PHP error log file
  file:
    path: /var/log/php/error.log
    owner: www-data
    group: root
    mode: 0644
    state: touch

- import_tasks: php-ini.yml
