---

- name: add packages.sury.org apt repo
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present
  register: phpaptrepo

- name: update apt
  apt: update_cache=yes
  when: phpaptrepo.changed

- name: install php dependencies
  apt: name={{ item }} state=present
  with_items:
    - 'php7.1'
    - 'php7.1-bcmath'
    - 'php7.1-bz2'
    - 'php7.1-cli'
    - 'php7.1-common'
    - 'php7.1-curl'
    - 'php7.1-dba'
    - 'php7.1-dev'
    - 'php7.1-gd'
    - 'php7.1-json'
    - 'php7.1-ldap'
    - 'php7.1-mbstring'
    - 'php7.1-mcrypt'
    - 'php7.1-mysql'
    - 'php7.1-opcache'
    - 'php7.1-readline'
    - 'php7.1-soap'
    - 'php7.1-xml'
    - 'php7.1-zip'
    - 'php7.1-pgsql'
    - 'php-memcached'
    - 'libapache2-mod-php7.1'
    - 'php-redis'
    - 'php-imagick'
    - 'php-pear'
    - 'php-uploadprogress'
    - 'imagemagick'

- name: install redis
  apt:
    name: redis-server
    state: present

- name: install memcached
  apt:
    name: memcached
    state: present

- name: create php log dir
  file:
    path: /var/log/php
    state: directory
    mode: 0755
    owner: www-data
    group: root

- name: create PHP error log file
  file:
    path: /var/log/php/error.log
    owner: www-data
    group: root
    mode: 0644
    state: touch

- import_tasks: php-ini.yml
