---

- name: install postgres
  apt:
    name: postgresql
    state: present

- name: install postgres-contrib
  apt:
    name: postgresql-contrib
    state: present

- name: install python-psycopg2
  apt:
    name: python-psycopg2
    state: present

- name: start postgres service
  shell: service postgresql start

- name: create postgres user
  become_user: postgres
  postgresql_user:
    name: root
    password: strongpassword
    role_attr_flags: CREATEDB,CREATEROLE,SUPERUSER,LOGIN

- name: create postgres database
  become_user: postgres
  postgresql_db:
    name: drupal
    owner: root

- name: add postgres.cnf file for root
  template: src=postgres.cnf.j2 dest=/root/.postgres.cnf owner=root mode=0600

- name: ensure postgres is stopped
  shell: service postgresql stop
