---

- name: install drush
  get_url:
    url: https://github.com/drush-ops/drush/releases/download/8.1.18/drush.phar
    dest: /usr/local/bin/drush
    mode: 0755

- name: add drupal console install script
  copy:
    src: install-drupal-console
    dest: /root/install-drupal-console
    mode: 0750

- name: run drupal console install
  command: /root/install-drupal-console
  args:
    creates: /usr/local/bin/drupal

- name: add composer install script
  copy:
    src: install-composer
    dest: /root/install-composer
    mode: 0750

- name: run composer install
  command: /root/install-composer
  args:
    creates: /usr/local/bin/composer
