---

- name: Add zivtech gpg key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x8e8904a002e048f5
    id: "02e048f5"

- name: Add zivtech apt repository.
  apt_repository:
    repo: deb http://apt.zivtech.com stable main trusty
    state: present
  register: zivtechaptrepo

- name: Add openjdk apt repository.
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    state: 'present'
  register: jdkaptrepo

- name: Update apt repositories.
  apt:
    update_cache: yes

- name: Install java apt package.
  apt:
    name: openjdk-8-jre
    state: present

- name: Install solr apt package.
  apt:
    name: solr
    state: present

- name: Add create-solr-instance script.
  copy:
    src: create-solr-instance
    dest: /usr/local/bin/create-solr-instance
    owner: root
    group: root
    mode: 0755

- name: Add remove-solr-instance script.
  copy:
    src: remove-solr-instance
    dest: /usr/local/bin/remove-solr-instance
    owner: root
    group: root
    mode: 0755

- name: ensure solr service is started
  service:
    name: solr
    state: started

- name: Create default solr instance.
  command: create-solr-instance solr /opt/solr/server/solr/configsets/search_api_solr_8.x-1.0

- name: ensure solr service is stopped
  service:
    name: solr
    state: stopped
